spring.application.name=park-api
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/park_api?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=park_api
spring.datasource.password=parkapi123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.flyway.locations=classpath:db/migration


# classpath:db/testedata

# # spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl-auto=create

# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create

# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql
# spring.jpa.database=mysql
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
# spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.open-in-view=false

# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR
